const std = @import("std");
const diagnostics = @import("kira_diagnostics");
const shader_model = @import("kira_shader_model");
const shader_ir = @import("kira_shader_ir");

pub const LoweredShader = struct {
    shader_name: []const u8,
    vertex_source: ?[]const u8 = null,
    fragment_source: ?[]const u8 = null,
};

pub fn lowerShader(
    allocator: std.mem.Allocator,
    program: shader_ir.Program,
    shader_decl: shader_ir.ShaderDecl,
    out_diagnostics: *std.array_list.Managed(diagnostics.Diagnostic),
) !LoweredShader {
    if (shader_decl.kind == .compute) {
        try diagnostics.appendOwned(allocator, out_diagnostics, .{
            .severity = .@"error",
            .code = "KSL122",
            .title = "compute shaders are not supported by the WGSL graphics backend",
            .message = "The current WGSL lowering path is scoped to graphics shaders for the WebGPU/Sokol WGPU render pipeline.",
            .help = "Use a graphics shader for WGSL today, or add a compute-capable WGSL lowering path before building this shader.",
        });
        return error.DiagnosticsEmitted;
    }

    const vertex_stage = findStage(shader_decl.stages, .vertex) orelse return error.InvalidArguments;
    const fragment_stage = findStage(shader_decl.stages, .fragment);

    var lowerer = Lowerer{
        .allocator = allocator,
        .program = &program,
        .shader = &shader_decl,
    };

    return .{
        .shader_name = shader_decl.name,
        .vertex_source = try lowerer.emitStage(vertex_stage),
        .fragment_source = if (fragment_stage) |stage| try lowerer.emitStage(stage) else null,
    };
}

const Lowerer = struct {
    allocator: std.mem.Allocator,
    program: *const shader_ir.Program,
    shader: *const shader_ir.ShaderDecl,

    fn emitStage(self: *Lowerer, stage: shader_ir.StageDecl) ![]const u8 {
        var out: std.Io.Writer.Allocating = .init(self.allocator);
        try out.writer.writeAll("// generated by Kira KSL WGSL backend\n\n");
        try self.emitStructs(&out.writer);
        try self.emitOptions(&out.writer);
        try self.emitResources(&out.writer);
        try self.emitHelpers(&out.writer);
        try self.emitFunction(&out.writer, stage.entry);
        try self.emitStageEntry(&out.writer, stage);
        return out.toOwnedSlice();
    }

    fn emitStructs(self: *Lowerer, writer: anytype) !void {
        for (self.program.types) |type_decl| {
            try writer.print("struct {s} {{\n", .{sanitizeName(type_decl.name)});
            var location: u32 = 0;
            for (type_decl.fields) |field_decl| {
                if (self.interfaceFieldAttribute(type_decl.name, field_decl, location)) |attribute| {
                    try writer.print("    {s} ", .{attribute});
                    if (field_decl.builtin == null) location += 1;
                } else if (isInterfaceType(self.shader.stages, type_decl.name) and field_decl.builtin == null) {
                    try writer.print("    @location({d}) ", .{location});
                    location += 1;
                } else {
                    try writer.writeAll("    ");
                }
                try writer.print("{s}: {s},\n", .{ sanitizeName(field_decl.name), try wgslTypeName(self.allocator, field_decl.ty) });
            }
            try writer.writeAll("};\n\n");
        }
    }

    fn interfaceFieldAttribute(self: *Lowerer, type_name: []const u8, field_decl: shader_ir.FieldDecl, location: u32) ?[]const u8 {
        if (!isInterfaceType(self.shader.stages, type_name)) return null;
        if (field_decl.builtin) |builtin| return wgslBuiltinAttribute(builtin);
        return std.fmt.allocPrint(self.allocator, "@location({d})", .{location}) catch null;
    }

    fn emitOptions(self: *Lowerer, writer: anytype) !void {
        for (self.shader.options) |option_decl| {
            try writer.print("const {s}: {s} = ", .{ sanitizeName(option_decl.name), try wgslTypeName(self.allocator, option_decl.ty) });
            try emitConstValue(writer, option_decl.default_value);
            try writer.writeAll(";\n");
        }
        if (self.shader.options.len != 0) try writer.writeByte('\n');
    }

    fn emitResources(self: *Lowerer, writer: anytype) !void {
        for (self.shader.groups) |group_decl| {
            for (group_decl.resources) |resource_decl| {
                try writer.print("@group({d}) @binding({d}) ", .{ resource_decl.logical_group_index, resource_decl.logical_binding_index });
                switch (resource_decl.kind) {
                    .uniform => try writer.print("var<uniform> {s}: {s};\n", .{ sanitizeName(resource_decl.name), try wgslTypeName(self.allocator, resource_decl.ty) }),
                    .storage => {
                        const access = if (resource_decl.access == .read) "read" else "read_write";
                        try writer.print("var<storage, {s}> {s}: {s};\n", .{ access, sanitizeName(resource_decl.name), try wgslTypeName(self.allocator, resource_decl.ty) });
                    },
                    .texture => try writer.print("var {s}: {s};\n", .{ sanitizeName(resource_decl.name), try wgslTypeName(self.allocator, resource_decl.ty) }),
                    .sampler => try writer.print("var {s}: {s};\n", .{ sanitizeName(resource_decl.name), try wgslTypeName(self.allocator, resource_decl.ty) }),
                }
            }
        }
        if (self.shader.groups.len != 0) try writer.writeByte('\n');
    }

    fn emitHelpers(self: *Lowerer, writer: anytype) !void {
        for (self.program.functions) |function_decl| {
            try self.emitFunction(writer, function_decl);
        }
    }

    fn emitFunction(self: *Lowerer, writer: anytype, function_decl: shader_ir.FunctionDecl) !void {
        try writer.print("fn {s}(", .{sanitizeName(function_decl.name)});
        for (function_decl.params, 0..) |param_decl, index| {
            if (index != 0) try writer.writeAll(", ");
            try writer.print("{s}: {s}", .{ sanitizeName(param_decl.name), try wgslTypeName(self.allocator, param_decl.ty) });
        }
        try writer.writeByte(')');
        if (function_decl.return_type != .void) {
            try writer.print(" -> {s}", .{try wgslTypeName(self.allocator, function_decl.return_type)});
        }
        try writer.writeByte(' ');
        try emitBlock(self.allocator, writer, function_decl.body, 0);
        try writer.writeAll("\n\n");
    }

    fn emitStageEntry(self: *Lowerer, writer: anytype, stage: shader_ir.StageDecl) !void {
        try writer.print("@{s}\n", .{@tagName(stage.kind)});
        try writer.print("fn {s}(", .{stageEntryName(self.allocator, self.shader.name, stage.kind)});
        if (stage.input_type) |input_type_name| {
            try writer.print("kira_input: {s}", .{sanitizeName(input_type_name)});
        }
        try writer.writeByte(')');
        if (stage.output_type) |output_type_name| {
            try writer.print(" -> {s}", .{sanitizeName(output_type_name)});
        }
        try writer.writeAll(" {\n");
        try writer.print("    ", .{});
        if (stage.output_type != null) try writer.writeAll("return ");
        try writer.print("{s}(", .{sanitizeName(stage.entry.name)});
        if (stage.input_type != null) try writer.writeAll("kira_input");
        try writer.writeAll(");\n");
        try writer.writeAll("}\n");
    }
};

fn emitBlock(allocator: std.mem.Allocator, writer: anytype, block: shader_ir.Block, indent_level: usize) anyerror!void {
    try writer.writeAll("{\n");
    for (block.statements) |statement| {
        try emitIndent(writer, indent_level + 1);
        try emitStatement(allocator, writer, statement, indent_level + 1);
    }
    try emitIndent(writer, indent_level);
    try writer.writeAll("}");
}

fn emitStatement(allocator: std.mem.Allocator, writer: anytype, statement: shader_ir.Statement, indent_level: usize) anyerror!void {
    switch (statement) {
        .let_stmt => |let_stmt| {
            try writer.print("var {s}: {s}", .{ sanitizeName(let_stmt.name), try wgslTypeName(allocator, let_stmt.ty) });
            if (let_stmt.value) |value| {
                try writer.writeAll(" = ");
                try emitExpr(allocator, writer, value);
            }
            try writer.writeAll(";\n");
        },
        .assign_stmt => |assign_stmt| {
            try emitExpr(allocator, writer, assign_stmt.target);
            try writer.writeAll(" = ");
            try emitExpr(allocator, writer, assign_stmt.value);
            try writer.writeAll(";\n");
        },
        .expr_stmt => |expr_stmt| {
            try emitExpr(allocator, writer, expr_stmt.expr);
            try writer.writeAll(";\n");
        },
        .return_stmt => |return_stmt| {
            if (return_stmt.value) |value| {
                try writer.writeAll("return ");
                try emitExpr(allocator, writer, value);
                try writer.writeAll(";\n");
            } else {
                try writer.writeAll("return;\n");
            }
        },
        .if_stmt => |if_stmt| {
            try writer.writeAll("if (");
            try emitExpr(allocator, writer, if_stmt.condition);
            try writer.writeAll(") ");
            try emitBlock(allocator, writer, if_stmt.then_block, indent_level);
            if (if_stmt.else_block) |else_block| {
                try writer.writeAll(" else ");
                try emitBlock(allocator, writer, else_block, indent_level);
            }
            try writer.writeAll("\n");
        },
        .while_stmt => |while_stmt| {
            try writer.writeAll("while (");
            try emitExpr(allocator, writer, while_stmt.condition);
            try writer.writeAll(") ");
            try emitBlock(allocator, writer, while_stmt.body, indent_level);
            try writer.writeAll("\n");
        },
    }
}

fn emitExpr(allocator: std.mem.Allocator, writer: anytype, expr: *const shader_ir.Expr) anyerror!void {
    switch (expr.node) {
        .const_value => |value| try emitConstValue(writer, value),
        .name => |name_ref| try writer.writeAll(sanitizeName(name_ref.name)),
        .unary => |unary_expr| {
            try writer.writeAll(switch (unary_expr.op) {
                .neg => "-",
                .not => "!",
            });
            try emitExpr(allocator, writer, unary_expr.operand);
        },
        .binary => |binary_expr| {
            try writer.writeByte('(');
            try emitExpr(allocator, writer, binary_expr.left);
            try writer.writeAll(switch (binary_expr.op) {
                .add => " + ",
                .sub => " - ",
                .mul => " * ",
                .div => " / ",
                .less => " < ",
                .less_equal => " <= ",
                .greater => " > ",
                .greater_equal => " >= ",
                .equal => " == ",
                .not_equal => " != ",
            });
            try emitExpr(allocator, writer, binary_expr.right);
            try writer.writeByte(')');
        },
        .member => |member_expr| {
            try emitExpr(allocator, writer, member_expr.object);
            try writer.print(".{s}", .{sanitizeName(member_expr.name)});
        },
        .index => |index_expr| {
            try emitExpr(allocator, writer, index_expr.object);
            try writer.writeByte('[');
            try emitExpr(allocator, writer, index_expr.index);
            try writer.writeByte(']');
        },
        .call => |call_expr| switch (call_expr.callee) {
            .constructor => |ty| {
                try writer.print("{s}(", .{try wgslTypeName(allocator, ty)});
                try emitCallArgs(allocator, writer, call_expr.args);
                try writer.writeByte(')');
            },
            .function => |function_name| {
                try writer.print("{s}(", .{sanitizeName(function_name.name)});
                try emitCallArgs(allocator, writer, call_expr.args);
                try writer.writeByte(')');
            },
            .intrinsic => |intrinsic| switch (intrinsic) {
                .mul => {
                    try writer.writeByte('(');
                    try emitExpr(allocator, writer, call_expr.args[0]);
                    try writer.writeAll(" * ");
                    try emitExpr(allocator, writer, call_expr.args[1]);
                    try writer.writeByte(')');
                },
                .normalize => {
                    try writer.writeAll("normalize(");
                    try emitCallArgs(allocator, writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .dot => {
                    try writer.writeAll("dot(");
                    try emitCallArgs(allocator, writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .length, .pow, .sin, .atan2, .smoothstep => {
                    try writer.print("{s}(", .{@tagName(intrinsic)});
                    try emitCallArgs(allocator, writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .sample => {
                    try writer.writeAll("textureSample(");
                    try emitCallArgs(allocator, writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .load => {
                    // texelFetch: unfiltered integer-coordinate read.
                    try writer.writeAll("textureLoad(");
                    try emitExpr(allocator, writer, call_expr.args[0]);
                    try writer.writeAll(", vec2<i32>(");
                    try emitExpr(allocator, writer, call_expr.args[1]);
                    try writer.writeAll("), 0)");
                },
            },
        },
    }
}

fn emitCallArgs(allocator: std.mem.Allocator, writer: anytype, args: []const *shader_ir.Expr) anyerror!void {
    for (args, 0..) |arg, index| {
        if (index != 0) try writer.writeAll(", ");
        try emitExpr(allocator, writer, arg);
    }
}

fn emitConstValue(writer: anytype, value: shader_ir.ConstValue) !void {
    switch (value) {
        .bool => |bool_value| try writer.writeAll(if (bool_value) "true" else "false"),
        .int => |int_value| try writer.print("{d}", .{int_value}),
        .uint => |uint_value| try writer.print("{d}u", .{uint_value}),
        .float => |float_value| try emitFloatValue(writer, float_value),
    }
}

fn emitFloatValue(writer: anytype, value: f64) !void {
    try writer.print("{d}", .{value});
    if (@floor(value) == value) try writer.writeAll(".0");
}

fn emitIndent(writer: anytype, level: usize) !void {
    for (0..level) |_| try writer.writeAll("    ");
}

fn wgslTypeName(allocator: std.mem.Allocator, ty: shader_model.Type) ![]const u8 {
    return switch (ty) {
        .void => "void",
        .scalar => switch (ty.scalar) {
            .bool => "bool",
            .int => "i32",
            .uint => "u32",
            .float => "f32",
        },
        .vector => try std.fmt.allocPrint(allocator, "vec{d}<{s}>", .{ ty.vector.width, try wgslScalarName(ty.vector.scalar) }),
        .matrix => try std.fmt.allocPrint(allocator, "mat{d}x{d}<f32>", .{ ty.matrix.columns, ty.matrix.rows }),
        .struct_ref => sanitizeName(ty.struct_ref),
        .texture => try wgslTextureName(allocator, ty.texture),
        .sampler => switch (ty.sampler) {
            .filtering => "sampler",
            .comparison => "sampler_comparison",
        },
        .runtime_array => try std.fmt.allocPrint(allocator, "array<{s}>", .{try wgslTypeName(allocator, ty.runtime_array.*)}),
    };
}

fn wgslScalarName(scalar: shader_model.ScalarType) ![]const u8 {
    return switch (scalar) {
        .bool => "bool",
        .int => "i32",
        .uint => "u32",
        .float => "f32",
    };
}

fn wgslTextureName(allocator: std.mem.Allocator, texture: shader_model.TextureDimension) ![]const u8 {
    _ = allocator;
    return switch (texture) {
        .texture_2d => "texture_2d<f32>",
        .texture_2d_uint => "texture_2d<u32>",
        .texture_cube => "texture_cube<f32>",
        .depth_2d => "texture_depth_2d",
    };
}

fn wgslBuiltinAttribute(builtin: shader_model.Builtin) []const u8 {
    return switch (builtin) {
        .position => "@builtin(position)",
        .vertex_index => "@builtin(vertex_index)",
        .instance_index => "@builtin(instance_index)",
        .front_facing => "@builtin(front_facing)",
        .frag_coord => "@builtin(position)",
        .thread_id => "@builtin(global_invocation_id)",
        .local_id => "@builtin(local_invocation_id)",
        .group_id => "@builtin(workgroup_id)",
        .local_index => "@builtin(local_invocation_index)",
    };
}

fn isInterfaceType(stages: []const shader_ir.StageDecl, type_name: []const u8) bool {
    for (stages) |stage| {
        if (stage.input_type) |input_type| {
            if (std.mem.eql(u8, input_type, type_name)) return true;
        }
        if (stage.output_type) |output_type| {
            if (std.mem.eql(u8, output_type, type_name)) return true;
        }
    }
    return false;
}

fn findStage(stages: []const shader_ir.StageDecl, stage: shader_model.Stage) ?shader_ir.StageDecl {
    for (stages) |stage_decl| {
        if (stage_decl.kind == stage) return stage_decl;
    }
    return null;
}

fn sanitizeName(name: []const u8) []const u8 {
    if (reservedWgslReplacement(name)) |replacement| return replacement;
    return name;
}

fn reservedWgslReplacement(name: []const u8) ?[]const u8 {
    const reserved = [_]struct { name: []const u8, replacement: []const u8 }{
        .{ .name = "array", .replacement = "kira_array" },
        .{ .name = "bool", .replacement = "kira_bool" },
        .{ .name = "break", .replacement = "kira_break" },
        .{ .name = "case", .replacement = "kira_case" },
        .{ .name = "const", .replacement = "kira_const" },
        .{ .name = "continue", .replacement = "kira_continue" },
        .{ .name = "default", .replacement = "kira_default" },
        .{ .name = "else", .replacement = "kira_else" },
        .{ .name = "false", .replacement = "kira_false" },
        .{ .name = "fn", .replacement = "kira_fn" },
        .{ .name = "for", .replacement = "kira_for" },
        .{ .name = "function", .replacement = "kira_function" },
        .{ .name = "if", .replacement = "kira_if" },
        .{ .name = "let", .replacement = "kira_let" },
        .{ .name = "loop", .replacement = "kira_loop" },
        .{ .name = "override", .replacement = "kira_override" },
        .{ .name = "return", .replacement = "kira_return" },
        .{ .name = "struct", .replacement = "kira_struct" },
        .{ .name = "switch", .replacement = "kira_switch" },
        .{ .name = "true", .replacement = "kira_true" },
        .{ .name = "var", .replacement = "kira_var" },
        .{ .name = "while", .replacement = "kira_while" },
    };
    for (reserved) |entry| {
        if (std.mem.eql(u8, name, entry.name)) return entry.replacement;
    }
    return null;
}

fn stageEntryName(allocator: std.mem.Allocator, shader_name: []const u8, stage: shader_model.Stage) []const u8 {
    return std.fmt.allocPrint(allocator, "{s}__{s}__main", .{ sanitizeName(shader_name), @tagName(stage) }) catch shader_name;
}

test "sanitizes WGSL reserved local names" {
    try std.testing.expectEqualStrings("kira_var", sanitizeName("var"));
    try std.testing.expectEqualStrings("kira_fn", sanitizeName("fn"));
    try std.testing.expectEqualStrings("result", sanitizeName("result"));
}
