[library]
name = "kira_main"
link_mode = "dynamic"
abi = "c"

[headers]
entrypoint = "../../packages/kira_main/include/kira_main.h"
include_dirs = ["../../packages/kira_main/include"]

[autobinding]
module = "kira_api"
output = "../bindings/kira_api/kira_api.kira"
headers = ["../../packages/kira_main/include/kira_main.h"]

[bindings]
mode = "all_public"

[target.x86_64-windows-msvc]
dynamic_lib = ""

[target.x86_64-linux-gnu]
dynamic_lib = ""

[target.aarch64-macos-none]
dynamic_lib = ""

[target.aarch64-ios-none]
dynamic_lib = ""

[target.aarch64-ios-simulator]
dynamic_lib = ""

[target.wasm32-emscripten-unknown]
dynamic_lib = ""
