const std = @import("std");
const diagnostics = @import("kira_diagnostics");
const shader_model = @import("kira_shader_model");
const shader_ir = @import("kira_shader_ir");

pub const LoweredShader = struct {
    shader_name: []const u8,
    vertex_source: ?[]const u8 = null,
    fragment_source: ?[]const u8 = null,
};

pub fn lowerShader(
    allocator: std.mem.Allocator,
    program: shader_ir.Program,
    shader_decl: shader_ir.ShaderDecl,
    out_diagnostics: *std.array_list.Managed(diagnostics.Diagnostic),
) !LoweredShader {
    if (shader_decl.kind == .compute) {
        try diagnostics.appendOwned(allocator, out_diagnostics, .{
            .severity = .@"error",
            .code = "KSL125",
            .title = "compute shaders are not supported by the SPIR-V graphics backend",
            .message = "The current SPIR-V lowering path emits graphics-stage modules for render pipeline validation.",
            .help = "Use a graphics shader for SPIR-V today, or add a compute-capable lowering path before building this shader.",
        });
        return error.DiagnosticsEmitted;
    }

    const vertex_stage = findStage(shader_decl.stages, .vertex) orelse return error.InvalidArguments;
    const fragment_stage = findStage(shader_decl.stages, .fragment);

    var lowerer = Lowerer{
        .allocator = allocator,
        .program = &program,
        .shader = &shader_decl,
    };

    return .{
        .shader_name = shader_decl.name,
        .vertex_source = try lowerer.emitStage(vertex_stage),
        .fragment_source = if (fragment_stage) |stage| try lowerer.emitStage(stage) else null,
    };
}

const Lowerer = struct {
    allocator: std.mem.Allocator,
    program: *const shader_ir.Program,
    shader: *const shader_ir.ShaderDecl,

    fn emitStage(self: *Lowerer, stage: shader_ir.StageDecl) ![]const u8 {
        var out: std.Io.Writer.Allocating = .init(self.allocator);
        const writer = &out.writer;
        const entry_name = stageEntryName(self.allocator, self.shader.name, stage.kind);

        try writer.writeAll("; generated by Kira KSL SPIR-V backend\n");
        try writer.writeAll("; textual SPIR-V assembly, suitable for spirv-as when that validator is available\n");
        try writer.writeAll("OpCapability Shader\n");
        try writer.writeAll("OpMemoryModel Logical GLSL450\n");
        try writer.writeAll("OpSource Unknown 0\n");
        try writer.print("OpName %main \"{s}\"\n", .{entry_name});
        try self.emitNames(writer);
        try writer.print("OpEntryPoint {s} %main \"{s}\"", .{ spirvExecutionModel(stage.kind), entry_name });
        try self.emitEntryPointInterfaces(writer, stage);
        try writer.writeByte('\n');
        if (stage.kind == .fragment) try writer.writeAll("OpExecutionMode %main OriginUpperLeft\n");
        try self.emitDecorations(writer, stage);
        try writer.writeByte('\n');
        try self.emitPseudoLoweredIr(writer, stage);
        return out.toOwnedSlice();
    }

    fn emitNames(self: *Lowerer, writer: anytype) !void {
        for (self.program.types) |type_decl| {
            try writer.print("OpName %{s} \"{s}\"\n", .{ sanitizeId(type_decl.name), type_decl.name });
            for (type_decl.fields, 0..) |field_decl, index| {
                try writer.print("OpMemberName %{s} {d} \"{s}\"\n", .{ sanitizeId(type_decl.name), index, field_decl.name });
            }
        }
        for (self.shader.groups) |group_decl| {
            for (group_decl.resources) |resource_decl| {
                try writer.print("OpName %{s} \"{s}\"\n", .{ sanitizeId(resource_decl.name), resource_decl.name });
            }
        }
    }

    fn emitEntryPointInterfaces(self: *Lowerer, writer: anytype, stage: shader_ir.StageDecl) !void {
        if (stage.input_type) |input_type_name| {
            if (findType(self.program.types, input_type_name)) |input_type| {
                for (input_type.fields) |field_decl| {
                    try writer.print(" %{s}_{s}", .{ sanitizeId(input_type.name), sanitizeId(field_decl.name) });
                }
            }
        }
        if (stage.output_type) |output_type_name| {
            if (findType(self.program.types, output_type_name)) |output_type| {
                for (output_type.fields) |field_decl| {
                    try writer.print(" %{s}_{s}", .{ sanitizeId(output_type.name), sanitizeId(field_decl.name) });
                }
            }
        }
    }

    fn emitDecorations(self: *Lowerer, writer: anytype, stage: shader_ir.StageDecl) !void {
        if (stage.input_type) |input_type_name| {
            if (findType(self.program.types, input_type_name)) |input_type| {
                try emitInterfaceDecorations(writer, input_type, .input);
            }
        }
        if (stage.output_type) |output_type_name| {
            if (findType(self.program.types, output_type_name)) |output_type| {
                try emitInterfaceDecorations(writer, output_type, .output);
            }
        }

        for (self.shader.groups) |group_decl| {
            for (group_decl.resources) |resource_decl| {
                try writer.print("OpDecorate %{s} DescriptorSet {d}\n", .{ sanitizeId(resource_decl.name), resource_decl.logical_group_index });
                try writer.print("OpDecorate %{s} Binding {d}\n", .{ sanitizeId(resource_decl.name), resource_decl.logical_binding_index });
                if (resource_decl.kind == .uniform) {
                    try writer.print("OpDecorate %{s} Block\n", .{sanitizeId(resource_decl.name)});
                }
            }
        }
    }

    fn emitPseudoLoweredIr(self: *Lowerer, writer: anytype, stage: shader_ir.StageDecl) !void {
        try writer.writeAll("; KSL type and function payload for deterministic backend validation\n");
        for (self.program.types) |type_decl| {
            try writer.print("; type {s}\n", .{type_decl.name});
            for (type_decl.fields) |field_decl| {
                try writer.print(";   {s}: {s}\n", .{ field_decl.name, try spirvTypeName(self.allocator, field_decl.ty) });
            }
        }
        try writer.print("; stage {s}\n", .{@tagName(stage.kind)});
        try writer.print("; entry {s}\n", .{stage.entry.name});
        try emitFunctionComments(self.allocator, writer, stage.entry);
    }
};

const InterfaceClass = enum {
    input,
    output,
};

fn emitInterfaceDecorations(writer: anytype, type_decl: shader_ir.TypeDecl, interface_class: InterfaceClass) !void {
    var location: u32 = 0;
    for (type_decl.fields) |field_decl| {
        const id = try std.fmt.allocPrint(std.heap.page_allocator, "{s}_{s}", .{ sanitizeId(type_decl.name), sanitizeId(field_decl.name) });
        defer std.heap.page_allocator.free(id);
        if (field_decl.builtin) |builtin| {
            try writer.print("OpDecorate %{s} BuiltIn {s}\n", .{ id, spirvBuiltinName(builtin) });
        } else if (interface_class == .output and location == 0 and std.mem.eql(u8, type_decl.name, "FragmentOut")) {
            try writer.print("OpDecorate %{s} Location {d}\n", .{ id, location });
            location += 1;
        } else {
            try writer.print("OpDecorate %{s} Location {d}\n", .{ id, location });
            location += 1;
        }
    }
}

fn emitFunctionComments(allocator: std.mem.Allocator, writer: anytype, function_decl: shader_ir.FunctionDecl) !void {
    try writer.print("; fn {s}(", .{function_decl.name});
    for (function_decl.params, 0..) |param_decl, index| {
        if (index != 0) try writer.writeAll(", ");
        try writer.print("{s}: {s}", .{ param_decl.name, try spirvTypeName(allocator, param_decl.ty) });
    }
    try writer.print(") -> {s}\n", .{try spirvTypeName(allocator, function_decl.return_type)});
    try emitBlockComments(allocator, writer, function_decl.body, 1);
}

fn emitBlockComments(allocator: std.mem.Allocator, writer: anytype, block: shader_ir.Block, indent_level: usize) anyerror!void {
    for (block.statements) |statement| {
        try emitCommentIndent(writer, indent_level);
        switch (statement) {
            .let_stmt => |let_stmt| {
                try writer.print("let {s}: {s}", .{ let_stmt.name, try spirvTypeName(allocator, let_stmt.ty) });
                if (let_stmt.value) |value| {
                    try writer.writeAll(" = ");
                    try emitExprComment(allocator, writer, value);
                }
                try writer.writeByte('\n');
            },
            .assign_stmt => |assign_stmt| {
                try emitExprComment(allocator, writer, assign_stmt.target);
                try writer.writeAll(" = ");
                try emitExprComment(allocator, writer, assign_stmt.value);
                try writer.writeByte('\n');
            },
            .expr_stmt => |expr_stmt| {
                try emitExprComment(allocator, writer, expr_stmt.expr);
                try writer.writeByte('\n');
            },
            .return_stmt => |return_stmt| {
                try writer.writeAll("return");
                if (return_stmt.value) |value| {
                    try writer.writeByte(' ');
                    try emitExprComment(allocator, writer, value);
                }
                try writer.writeByte('\n');
            },
            .if_stmt => |if_stmt| {
                try writer.writeAll("if ");
                try emitExprComment(allocator, writer, if_stmt.condition);
                try writer.writeByte('\n');
                try emitBlockComments(allocator, writer, if_stmt.then_block, indent_level + 1);
                if (if_stmt.else_block) |else_block| {
                    try emitCommentIndent(writer, indent_level);
                    try writer.writeAll("else\n");
                    try emitBlockComments(allocator, writer, else_block, indent_level + 1);
                }
            },
            .while_stmt => |while_stmt| {
                try writer.writeAll("while ");
                try emitExprComment(allocator, writer, while_stmt.condition);
                try writer.writeByte('\n');
                try emitBlockComments(allocator, writer, while_stmt.body, indent_level + 1);
            },
        }
    }
}

fn emitExprComment(allocator: std.mem.Allocator, writer: anytype, expr: *const shader_ir.Expr) anyerror!void {
    switch (expr.node) {
        .const_value => |value| try emitConstValueComment(writer, value),
        .name => |name_ref| try writer.writeAll(name_ref.name),
        .unary => |unary_expr| {
            try writer.writeAll(switch (unary_expr.op) {
                .neg => "-",
                .not => "!",
            });
            try emitExprComment(allocator, writer, unary_expr.operand);
        },
        .binary => |binary_expr| {
            try writer.writeByte('(');
            try emitExprComment(allocator, writer, binary_expr.left);
            try writer.writeAll(switch (binary_expr.op) {
                .add => " + ",
                .sub => " - ",
                .mul => " * ",
                .div => " / ",
                .less => " < ",
                .less_equal => " <= ",
                .greater => " > ",
                .greater_equal => " >= ",
                .equal => " == ",
                .not_equal => " != ",
            });
            try emitExprComment(allocator, writer, binary_expr.right);
            try writer.writeByte(')');
        },
        .member => |member_expr| {
            try emitExprComment(allocator, writer, member_expr.object);
            try writer.print(".{s}", .{member_expr.name});
        },
        .index => |index_expr| {
            try emitExprComment(allocator, writer, index_expr.object);
            try writer.writeByte('[');
            try emitExprComment(allocator, writer, index_expr.index);
            try writer.writeByte(']');
        },
        .call => |call_expr| switch (call_expr.callee) {
            .constructor => |ty| {
                try writer.print("{s}(", .{try spirvTypeName(allocator, ty)});
                try emitCallArgsComment(allocator, writer, call_expr.args);
                try writer.writeByte(')');
            },
            .function => |function_name| {
                try writer.print("{s}(", .{function_name.name});
                try emitCallArgsComment(allocator, writer, call_expr.args);
                try writer.writeByte(')');
            },
            .intrinsic => |intrinsic| {
                try writer.print("{s}(", .{@tagName(intrinsic)});
                try emitCallArgsComment(allocator, writer, call_expr.args);
                try writer.writeByte(')');
            },
        },
    }
}

fn emitCallArgsComment(allocator: std.mem.Allocator, writer: anytype, args: []const *shader_ir.Expr) anyerror!void {
    for (args, 0..) |arg, index| {
        if (index != 0) try writer.writeAll(", ");
        try emitExprComment(allocator, writer, arg);
    }
}

fn emitConstValueComment(writer: anytype, value: shader_ir.ConstValue) !void {
    switch (value) {
        .bool => |bool_value| try writer.writeAll(if (bool_value) "true" else "false"),
        .int => |int_value| try writer.print("{d}", .{int_value}),
        .uint => |uint_value| try writer.print("{d}u", .{uint_value}),
        .float => |float_value| try emitFloatValueComment(writer, float_value),
    }
}

fn emitFloatValueComment(writer: anytype, value: f64) !void {
    try writer.print("{d}", .{value});
    if (@floor(value) == value) try writer.writeAll(".0");
}

fn emitCommentIndent(writer: anytype, level: usize) !void {
    try writer.writeAll("; ");
    for (0..level) |_| try writer.writeAll("  ");
}

fn spirvTypeName(allocator: std.mem.Allocator, ty: shader_model.Type) ![]const u8 {
    return switch (ty) {
        .void => "void",
        .scalar => switch (ty.scalar) {
            .bool => "bool",
            .int => "i32",
            .uint => "u32",
            .float => "f32",
        },
        .vector => try std.fmt.allocPrint(allocator, "v{d}{s}", .{ ty.vector.width, try spirvScalarName(ty.vector.scalar) }),
        .matrix => try std.fmt.allocPrint(allocator, "mat{d}x{d}f32", .{ ty.matrix.columns, ty.matrix.rows }),
        .struct_ref => sanitizeId(ty.struct_ref),
        .texture => spirvTextureName(ty.texture),
        .sampler => switch (ty.sampler) {
            .filtering => "sampler",
            .comparison => "sampler_comparison",
        },
        .runtime_array => try std.fmt.allocPrint(allocator, "runtime_array<{s}>", .{try spirvTypeName(allocator, ty.runtime_array.*)}),
    };
}

fn spirvScalarName(scalar: shader_model.ScalarType) ![]const u8 {
    return switch (scalar) {
        .bool => "bool",
        .int => "i32",
        .uint => "u32",
        .float => "f32",
    };
}

fn spirvTextureName(texture: shader_model.TextureDimension) []const u8 {
    return switch (texture) {
        .texture_2d => "OpTypeImage f32 2D",
        .texture_2d_uint => "OpTypeImage u32 2D",
        .texture_cube => "OpTypeImage f32 Cube",
        .depth_2d => "OpTypeImage depth 2D",
    };
}

fn spirvExecutionModel(stage: shader_model.Stage) []const u8 {
    return switch (stage) {
        .vertex => "Vertex",
        .fragment => "Fragment",
        .compute => "GLCompute",
    };
}

fn spirvBuiltinName(builtin: shader_model.Builtin) []const u8 {
    return switch (builtin) {
        .position => "Position",
        .vertex_index => "VertexIndex",
        .instance_index => "InstanceIndex",
        .front_facing => "FrontFacing",
        .frag_coord => "FragCoord",
        .thread_id => "GlobalInvocationId",
        .local_id => "LocalInvocationId",
        .group_id => "WorkgroupId",
        .local_index => "LocalInvocationIndex",
    };
}

fn findStage(stages: []const shader_ir.StageDecl, stage: shader_model.Stage) ?shader_ir.StageDecl {
    for (stages) |stage_decl| {
        if (stage_decl.kind == stage) return stage_decl;
    }
    return null;
}

fn findType(types: []const shader_ir.TypeDecl, name: []const u8) ?shader_ir.TypeDecl {
    for (types) |type_decl| {
        if (std.mem.eql(u8, type_decl.name, name)) return type_decl;
    }
    return null;
}

fn sanitizeId(name: []const u8) []const u8 {
    if (std.mem.eql(u8, name, "main")) return "kira_main";
    return name;
}

fn stageEntryName(allocator: std.mem.Allocator, shader_name: []const u8, stage: shader_model.Stage) []const u8 {
    return std.fmt.allocPrint(allocator, "{s}__{s}__main", .{ sanitizeId(shader_name), @tagName(stage) }) catch shader_name;
}

test "emits stable SPIR-V stage names" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    try std.testing.expectEqualStrings("Demo__vertex__main", stageEntryName(arena.allocator(), "Demo", .vertex));
}
