[library]
name = "glfw"
link_mode = "static"
abi = "c"

[headers]
include_dirs = ["include"]
defines = ["GLFW_INCLUDE_NONE"]

[target.x86_64-windows-msvc]
static_lib = "vendor/glfw/windows/x86_64/glfw3_mt.lib"

[target.x86_64-linux-gnu]
static_lib = "vendor/glfw/linux/x86_64/libglfw3.a"

[target.aarch64-macos]
static_lib = "vendor/glfw/macos/aarch64/libglfw3.a"
frameworks = ["Cocoa", "IOKit", "CoreVideo"]
