const std = @import("std");
const diagnostics = @import("kira_diagnostics");
const shader_model = @import("kira_shader_model");
const shader_ir = @import("kira_shader_ir");

pub const LoweredShader = struct {
    shader_name: []const u8,
    vertex_source: ?[]const u8 = null,
    fragment_source: ?[]const u8 = null,
    compute_source: ?[]const u8 = null,
};

pub fn lowerShader(
    allocator: std.mem.Allocator,
    program: shader_ir.Program,
    shader_decl: shader_ir.ShaderDecl,
    out_diagnostics: *std.array_list.Managed(diagnostics.Diagnostic),
) !LoweredShader {
    _ = out_diagnostics;
    var lowerer = Lowerer{
        .allocator = allocator,
        .program = &program,
        .shader = &shader_decl,
    };

    if (shader_decl.kind == .compute) {
        const compute_stage = findStage(shader_decl.stages, .compute) orelse return error.InvalidArguments;
        return .{
            .shader_name = shader_decl.name,
            .compute_source = try lowerer.emitStage(compute_stage),
        };
    }

    const vertex_stage = findStage(shader_decl.stages, .vertex) orelse return error.InvalidArguments;
    const fragment_stage = findStage(shader_decl.stages, .fragment);

    return .{
        .shader_name = shader_decl.name,
        .vertex_source = try lowerer.emitStage(vertex_stage),
        .fragment_source = if (fragment_stage) |stage| try lowerer.emitStage(stage) else null,
    };
}

const Lowerer = struct {
    allocator: std.mem.Allocator,
    program: *const shader_ir.Program,
    shader: *const shader_ir.ShaderDecl,

    fn emitStage(self: *Lowerer, stage: shader_ir.StageDecl) ![]const u8 {
        var out: std.Io.Writer.Allocating = .init(self.allocator);
        try out.writer.writeAll("// generated by Kira KSL HLSL backend\n\n");
        try self.emitStructs(&out.writer);
        try self.emitOptions(&out.writer);
        try self.emitResources(&out.writer);
        try self.emitHelpers(&out.writer);
        try self.emitFunction(&out.writer, stage.entry);
        try self.emitStageEntry(&out.writer, stage);
        return out.toOwnedSlice();
    }

    fn emitStructs(self: *Lowerer, writer: anytype) !void {
        for (self.program.types) |type_decl| {
            try writer.print("struct {s} {{\n", .{sanitizeName(type_decl.name)});
            var location: u32 = 0;
            for (type_decl.fields) |field_decl| {
                try writer.print("    {s} {s}", .{ hlslTypeName(field_decl.ty), sanitizeName(field_decl.name) });
                if (self.interfaceFieldSemantic(type_decl.name, field_decl, location)) |semantic| {
                    try writer.print(" : {s}", .{semantic});
                    if (field_decl.builtin == null) location += 1;
                } else if (isInterfaceType(self.shader.stages, type_decl.name) and field_decl.builtin == null) {
                    try writer.print(" : TEXCOORD{d}", .{location});
                    location += 1;
                }
                try writer.writeAll(";\n");
            }
            try writer.writeAll("};\n\n");
        }
    }

    fn interfaceFieldSemantic(self: *Lowerer, type_name: []const u8, field_decl: shader_ir.FieldDecl, location: u32) ?[]const u8 {
        if (!isInterfaceType(self.shader.stages, type_name)) return null;
        if (field_decl.builtin) |builtin| return hlslBuiltinSemantic(builtin);
        if (isFragmentOutputType(self.shader.stages, type_name)) {
            if (location == 0) return "SV_Target";
            return std.fmt.allocPrint(self.allocator, "SV_Target{d}", .{location}) catch null;
        }
        return std.fmt.allocPrint(self.allocator, "TEXCOORD{d}", .{location}) catch null;
    }

    fn emitOptions(self: *Lowerer, writer: anytype) !void {
        for (self.shader.options) |option_decl| {
            try writer.print("static const {s} {s} = ", .{ hlslTypeName(option_decl.ty), sanitizeName(option_decl.name) });
            try emitConstValue(writer, option_decl.default_value);
            try writer.writeAll(";\n");
        }
        if (self.shader.options.len != 0) try writer.writeByte('\n');
    }

    fn emitResources(self: *Lowerer, writer: anytype) !void {
        var uniform_slot: u32 = 0;
        var texture_slot: u32 = 0;
        var sampler_slot: u32 = 0;
        var storage_slot: u32 = 0;
        for (self.shader.groups) |group_decl| {
            for (group_decl.resources) |resource_decl| {
                switch (resource_decl.kind) {
                    .uniform => {
                        try writer.print("ConstantBuffer<{s}> {s} : register(b{d});\n", .{
                            hlslTypeName(resource_decl.ty),
                            sanitizeName(resource_decl.name),
                            uniform_slot,
                        });
                        uniform_slot += 1;
                    },
                    .storage => {
                        const prefix = if (resource_decl.access == .read) "StructuredBuffer" else "RWStructuredBuffer";
                        try writer.print("{s}<{s}> {s} : register(u{d});\n", .{
                            prefix,
                            hlslTypeName(resource_decl.ty),
                            sanitizeName(resource_decl.name),
                            storage_slot,
                        });
                        storage_slot += 1;
                    },
                    .texture => {
                        try writer.print("{s} {s} : register(t{d});\n", .{
                            hlslTextureName(resource_decl.ty.texture),
                            sanitizeName(resource_decl.name),
                            texture_slot,
                        });
                        texture_slot += 1;
                    },
                    .sampler => {
                        try writer.print("{s} {s} : register(s{d});\n", .{
                            hlslSamplerName(resource_decl.ty.sampler),
                            sanitizeName(resource_decl.name),
                            sampler_slot,
                        });
                        sampler_slot += 1;
                    },
                }
            }
        }
        if (uniform_slot + texture_slot + sampler_slot + storage_slot != 0) try writer.writeByte('\n');
    }

    fn emitHelpers(self: *Lowerer, writer: anytype) !void {
        for (self.program.functions) |function_decl| {
            try self.emitFunction(writer, function_decl);
        }
    }

    fn emitFunction(self: *Lowerer, writer: anytype, function_decl: shader_ir.FunctionDecl) !void {
        _ = self;
        try writer.print("{s} {s}(", .{ hlslTypeName(function_decl.return_type), sanitizeName(function_decl.name) });
        for (function_decl.params, 0..) |param_decl, index| {
            if (index != 0) try writer.writeAll(", ");
            try writer.print("{s} {s}", .{ hlslTypeName(param_decl.ty), sanitizeName(param_decl.name) });
        }
        try writer.writeAll(") ");
        try emitBlock(writer, function_decl.body, 0);
        try writer.writeAll("\n\n");
    }

    fn emitStageEntry(self: *Lowerer, writer: anytype, stage: shader_ir.StageDecl) !void {
        const entry_name = stageEntryName(self.allocator, self.shader.name, stage.kind);
        if (stage.kind == .compute) {
            const t = stage.threads orelse shader_ir.Threads{ .x = 64, .y = 1, .z = 1 };
            try writer.print("[numthreads({d}, {d}, {d})]\n", .{ t.x, t.y, t.z });
            try writer.print("void {s}(", .{entry_name});
            if (stage.input_type) |input_type_name| {
                try writer.print("{s} kira_input", .{sanitizeName(input_type_name)});
            }
            try writer.writeAll(") {\n    ");
            try writer.print("{s}(", .{sanitizeName(stage.entry.name)});
            if (stage.input_type != null) try writer.writeAll("kira_input");
            try writer.writeAll(");\n}\n");
            return;
        }
        const return_type = if (stage.output_type) |output_type_name| sanitizeName(output_type_name) else "void";
        try writer.print("{s} {s}(", .{ return_type, entry_name });
        if (stage.input_type) |input_type_name| {
            try writer.print("{s} kira_input", .{sanitizeName(input_type_name)});
        }
        try writer.writeAll(") {\n");
        try writer.writeAll("    ");
        if (stage.output_type != null) try writer.writeAll("return ");
        try writer.print("{s}(", .{sanitizeName(stage.entry.name)});
        if (stage.input_type != null) try writer.writeAll("kira_input");
        try writer.writeAll(");\n");
        try writer.writeAll("}\n");
    }
};

fn emitBlock(writer: anytype, block: shader_ir.Block, indent_level: usize) anyerror!void {
    try writer.writeAll("{\n");
    for (block.statements) |statement| {
        try emitIndent(writer, indent_level + 1);
        try emitStatement(writer, statement, indent_level + 1);
    }
    try emitIndent(writer, indent_level);
    try writer.writeAll("}");
}

fn emitStatement(writer: anytype, statement: shader_ir.Statement, indent_level: usize) anyerror!void {
    switch (statement) {
        .let_stmt => |let_stmt| {
            try writer.print("{s} {s}", .{ hlslTypeName(let_stmt.ty), sanitizeName(let_stmt.name) });
            if (let_stmt.value) |value| {
                try writer.writeAll(" = ");
                try emitExpr(writer, value);
            }
            try writer.writeAll(";\n");
        },
        .assign_stmt => |assign_stmt| {
            try emitExpr(writer, assign_stmt.target);
            try writer.writeAll(" = ");
            try emitExpr(writer, assign_stmt.value);
            try writer.writeAll(";\n");
        },
        .expr_stmt => |expr_stmt| {
            try emitExpr(writer, expr_stmt.expr);
            try writer.writeAll(";\n");
        },
        .return_stmt => |return_stmt| {
            if (return_stmt.value) |value| {
                try writer.writeAll("return ");
                try emitExpr(writer, value);
                try writer.writeAll(";\n");
            } else {
                try writer.writeAll("return;\n");
            }
        },
        .if_stmt => |if_stmt| {
            try writer.writeAll("if (");
            try emitExpr(writer, if_stmt.condition);
            try writer.writeAll(") ");
            try emitBlock(writer, if_stmt.then_block, indent_level);
            if (if_stmt.else_block) |else_block| {
                try writer.writeAll(" else ");
                try emitBlock(writer, else_block, indent_level);
            }
            try writer.writeAll("\n");
        },
        .while_stmt => |while_stmt| {
            try writer.writeAll("while (");
            try emitExpr(writer, while_stmt.condition);
            try writer.writeAll(") ");
            try emitBlock(writer, while_stmt.body, indent_level);
            try writer.writeAll("\n");
        },
    }
}

fn emitExpr(writer: anytype, expr: *const shader_ir.Expr) anyerror!void {
    switch (expr.node) {
        .const_value => |value| try emitConstValue(writer, value),
        .name => |name_ref| try writer.writeAll(sanitizeName(name_ref.name)),
        .unary => |unary_expr| {
            try writer.writeAll(switch (unary_expr.op) {
                .neg => "-",
                .not => "!",
            });
            try emitExpr(writer, unary_expr.operand);
        },
        .binary => |binary_expr| {
            try writer.writeByte('(');
            try emitExpr(writer, binary_expr.left);
            try writer.writeAll(switch (binary_expr.op) {
                .add => " + ",
                .sub => " - ",
                .mul => " * ",
                .div => " / ",
                .less => " < ",
                .less_equal => " <= ",
                .greater => " > ",
                .greater_equal => " >= ",
                .equal => " == ",
                .not_equal => " != ",
            });
            try emitExpr(writer, binary_expr.right);
            try writer.writeByte(')');
        },
        .member => |member_expr| {
            try emitExpr(writer, member_expr.object);
            try writer.print(".{s}", .{sanitizeName(member_expr.name)});
        },
        .index => |index_expr| {
            try emitExpr(writer, index_expr.object);
            try writer.writeByte('[');
            try emitExpr(writer, index_expr.index);
            try writer.writeByte(']');
        },
        .call => |call_expr| switch (call_expr.callee) {
            .constructor => |ty| {
                try writer.print("{s}(", .{hlslTypeName(ty)});
                try emitCallArgs(writer, call_expr.args);
                try writer.writeByte(')');
            },
            .function => |function_name| {
                try writer.print("{s}(", .{sanitizeName(function_name.name)});
                try emitCallArgs(writer, call_expr.args);
                try writer.writeByte(')');
            },
            .intrinsic => |intrinsic| switch (intrinsic) {
                .mul => {
                    try writer.writeAll("mul(");
                    try emitCallArgs(writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .normalize => {
                    try writer.writeAll("normalize(");
                    try emitCallArgs(writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .dot => {
                    try writer.writeAll("dot(");
                    try emitCallArgs(writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .length, .pow, .sin, .atan2, .smoothstep => {
                    try writer.print("{s}(", .{@tagName(intrinsic)});
                    try emitCallArgs(writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .sample => {
                    const texture_name = switch (call_expr.args[0].node) {
                        .name => |name_ref| name_ref.name,
                        else => "unsupported_texture",
                    };
                    try writer.print("{s}.Sample(", .{sanitizeName(texture_name)});
                    try emitExpr(writer, call_expr.args[1]);
                    try writer.writeAll(", ");
                    try emitExpr(writer, call_expr.args[2]);
                    try writer.writeByte(')');
                },
                .load => {
                    // texelFetch: Texture2D.Load(int3(x, y, mip)).
                    const texture_name = switch (call_expr.args[0].node) {
                        .name => |name_ref| name_ref.name,
                        else => "unsupported_texture",
                    };
                    try writer.print("{s}.Load(int3(", .{sanitizeName(texture_name)});
                    try emitExpr(writer, call_expr.args[1]);
                    try writer.writeAll(", 0))");
                },
                .atomic_add => {
                    // NOTE: HLSL InterlockedAdd is statement-form; this expression
                    // emission is a placeholder until the D3D backend is verified.
                    try writer.writeAll("kira_atomic_add(");
                    try emitExpr(writer, call_expr.args[0]);
                    try writer.writeAll(", ");
                    try emitExpr(writer, call_expr.args[1]);
                    try writer.writeAll(", ");
                    try emitExpr(writer, call_expr.args[2]);
                    try writer.writeByte(')');
                },
            },
        },
    }
}

fn emitCallArgs(writer: anytype, args: []const *shader_ir.Expr) anyerror!void {
    for (args, 0..) |arg, index| {
        if (index != 0) try writer.writeAll(", ");
        try emitExpr(writer, arg);
    }
}

fn emitConstValue(writer: anytype, value: shader_ir.ConstValue) !void {
    switch (value) {
        .bool => |bool_value| try writer.writeAll(if (bool_value) "true" else "false"),
        .int => |int_value| try writer.print("{d}", .{int_value}),
        .uint => |uint_value| try writer.print("{d}u", .{uint_value}),
        .float => |float_value| try emitFloatValue(writer, float_value),
    }
}

fn emitFloatValue(writer: anytype, value: f64) !void {
    try writer.print("{d}", .{value});
    if (@floor(value) == value) try writer.writeAll(".0");
}

fn emitIndent(writer: anytype, level: usize) !void {
    for (0..level) |_| try writer.writeAll("    ");
}

fn hlslTypeName(ty: shader_model.Type) []const u8 {
    return switch (ty) {
        .void => "void",
        .scalar => switch (ty.scalar) {
            .bool => "bool",
            .int => "int",
            .uint => "uint",
            .float => "float",
        },
        .vector => switch (ty.vector.scalar) {
            .float => switch (ty.vector.width) {
                2 => "float2",
                3 => "float3",
                else => "float4",
            },
            .int => switch (ty.vector.width) {
                2 => "int2",
                3 => "int3",
                else => "int4",
            },
            .uint => switch (ty.vector.width) {
                2 => "uint2",
                3 => "uint3",
                else => "uint4",
            },
            .bool => switch (ty.vector.width) {
                2 => "bool2",
                3 => "bool3",
                else => "bool4",
            },
        },
        .matrix => "float4x4",
        .struct_ref => sanitizeName(ty.struct_ref),
        .texture => hlslTextureName(ty.texture),
        .sampler => hlslSamplerName(ty.sampler),
        .runtime_array => hlslTypeName(ty.runtime_array.*),
    };
}

fn hlslTextureName(texture: shader_model.TextureDimension) []const u8 {
    return switch (texture) {
        .texture_2d => "Texture2D<float4>",
        .texture_2d_uint => "Texture2D<uint>",
        .texture_cube => "TextureCube<float4>",
        .depth_2d => "Texture2D<float>",
    };
}

fn hlslSamplerName(sampler: shader_model.SamplerKind) []const u8 {
    return switch (sampler) {
        .filtering => "SamplerState",
        .comparison => "SamplerComparisonState",
    };
}

fn hlslBuiltinSemantic(builtin: shader_model.Builtin) []const u8 {
    return switch (builtin) {
        .position => "SV_Position",
        .vertex_index => "SV_VertexID",
        .instance_index => "SV_InstanceID",
        .front_facing => "SV_IsFrontFace",
        .frag_coord => "SV_Position",
        .thread_id => "SV_DispatchThreadID",
        .local_id => "SV_GroupThreadID",
        .group_id => "SV_GroupID",
        .local_index => "SV_GroupIndex",
    };
}

fn isInterfaceType(stages: []const shader_ir.StageDecl, type_name: []const u8) bool {
    for (stages) |stage| {
        if (stage.input_type) |input_type| {
            if (std.mem.eql(u8, input_type, type_name)) return true;
        }
        if (stage.output_type) |output_type| {
            if (std.mem.eql(u8, output_type, type_name)) return true;
        }
    }
    return false;
}

fn isFragmentOutputType(stages: []const shader_ir.StageDecl, type_name: []const u8) bool {
    for (stages) |stage| {
        if (stage.kind != .fragment) continue;
        if (stage.output_type) |output_type| {
            if (std.mem.eql(u8, output_type, type_name)) return true;
        }
    }
    return false;
}

fn findStage(stages: []const shader_ir.StageDecl, stage: shader_model.Stage) ?shader_ir.StageDecl {
    for (stages) |stage_decl| {
        if (stage_decl.kind == stage) return stage_decl;
    }
    return null;
}

fn sanitizeName(name: []const u8) []const u8 {
    if (reservedHlslReplacement(name)) |replacement| return replacement;
    return name;
}

fn reservedHlslReplacement(name: []const u8) ?[]const u8 {
    const reserved = [_]struct { name: []const u8, replacement: []const u8 }{
        .{ .name = "Buffer", .replacement = "kira_Buffer" },
        .{ .name = "ConstantBuffer", .replacement = "kira_ConstantBuffer" },
        .{ .name = "Texture2D", .replacement = "kira_Texture2D" },
        .{ .name = "SamplerState", .replacement = "kira_SamplerState" },
        .{ .name = "bool", .replacement = "kira_bool" },
        .{ .name = "break", .replacement = "kira_break" },
        .{ .name = "case", .replacement = "kira_case" },
        .{ .name = "cbuffer", .replacement = "kira_cbuffer" },
        .{ .name = "class", .replacement = "kira_class" },
        .{ .name = "const", .replacement = "kira_const" },
        .{ .name = "continue", .replacement = "kira_continue" },
        .{ .name = "default", .replacement = "kira_default" },
        .{ .name = "do", .replacement = "kira_do" },
        .{ .name = "else", .replacement = "kira_else" },
        .{ .name = "false", .replacement = "kira_false" },
        .{ .name = "float", .replacement = "kira_float" },
        .{ .name = "for", .replacement = "kira_for" },
        .{ .name = "if", .replacement = "kira_if" },
        .{ .name = "int", .replacement = "kira_int" },
        .{ .name = "in", .replacement = "kira_in" },
        .{ .name = "inout", .replacement = "kira_inout" },
        .{ .name = "out", .replacement = "kira_out" },
        .{ .name = "return", .replacement = "kira_return" },
        .{ .name = "SamplerComparisonState", .replacement = "kira_SamplerComparisonState" },
        .{ .name = "static", .replacement = "kira_static" },
        .{ .name = "struct", .replacement = "kira_struct" },
        .{ .name = "true", .replacement = "kira_true" },
        .{ .name = "uint", .replacement = "kira_uint" },
        .{ .name = "void", .replacement = "kira_void" },
        .{ .name = "while", .replacement = "kira_while" },
    };
    for (reserved) |entry| {
        if (std.mem.eql(u8, name, entry.name)) return entry.replacement;
    }
    return null;
}

fn stageEntryName(allocator: std.mem.Allocator, shader_name: []const u8, stage: shader_model.Stage) []const u8 {
    return std.fmt.allocPrint(allocator, "{s}__{s}__main", .{ sanitizeName(shader_name), @tagName(stage) }) catch shader_name;
}

test "sanitizes HLSL reserved local names" {
    try std.testing.expectEqualStrings("kira_float", sanitizeName("float"));
    try std.testing.expectEqualStrings("kira_cbuffer", sanitizeName("cbuffer"));
    try std.testing.expectEqualStrings("result", sanitizeName("result"));
}
