const std = @import("std");
const diagnostics = @import("kira_diagnostics");
const shader_model = @import("kira_shader_model");
const shader_ir = @import("kira_shader_ir");

pub const LoweredShader = struct {
    shader_name: []const u8,
    vertex_source: ?[]const u8 = null,
    fragment_source: ?[]const u8 = null,
    compute_source: ?[]const u8 = null,
};

pub fn lowerShader(
    allocator: std.mem.Allocator,
    program: shader_ir.Program,
    shader_decl: shader_ir.ShaderDecl,
    out_diagnostics: *std.array_list.Managed(diagnostics.Diagnostic),
) !LoweredShader {
    _ = out_diagnostics;
    var lowerer = Lowerer{
        .allocator = allocator,
        .program = &program,
        .shader = &shader_decl,
    };

    if (shader_decl.kind == .compute) {
        const compute_stage = findStage(shader_decl.stages, .compute) orelse return error.InvalidArguments;
        return .{
            .shader_name = shader_decl.name,
            .compute_source = try lowerer.emitStage(compute_stage),
        };
    }

    const vertex_stage = findStage(shader_decl.stages, .vertex) orelse return error.InvalidArguments;
    const fragment_stage = findStage(shader_decl.stages, .fragment);

    return .{
        .shader_name = shader_decl.name,
        .vertex_source = try lowerer.emitStage(vertex_stage),
        .fragment_source = if (fragment_stage) |stage| try lowerer.emitStage(stage) else null,
    };
}

const Lowerer = struct {
    allocator: std.mem.Allocator,
    program: *const shader_ir.Program,
    shader: *const shader_ir.ShaderDecl,
    // Storage resources touched by atomicAdd: bound as `device atomic_uint*`
    // (Metal atomics require atomic types; such a buffer is atomics-only).
    atomic_resources: std.StringHashMapUnmanaged(void) = .{},

    fn collectAtomicExpr(self: *Lowerer, expr: *const shader_ir.Expr) !void {
        switch (expr.node) {
            .call => |call_expr| {
                if (call_expr.callee == .intrinsic and call_expr.callee.intrinsic == .atomic_add) {
                    if (call_expr.args.len > 0 and call_expr.args[0].node == .name) {
                        try self.atomic_resources.put(self.allocator, call_expr.args[0].node.name.name, {});
                    }
                }
                for (call_expr.args) |arg| try self.collectAtomicExpr(arg);
            },
            .unary => |u| try self.collectAtomicExpr(u.operand),
            .binary => |b| {
                try self.collectAtomicExpr(b.left);
                try self.collectAtomicExpr(b.right);
            },
            .member => |m| try self.collectAtomicExpr(m.object),
            .index => |ix| {
                try self.collectAtomicExpr(ix.object);
                try self.collectAtomicExpr(ix.index);
            },
            else => {},
        }
    }

    fn collectAtomicBlock(self: *Lowerer, block: shader_ir.Block) !void {
        for (block.statements) |statement| {
            switch (statement) {
                .let_stmt => |st| if (st.value) |v| try self.collectAtomicExpr(v),
                .assign_stmt => |st| {
                    try self.collectAtomicExpr(st.target);
                    try self.collectAtomicExpr(st.value);
                },
                .expr_stmt => |st| try self.collectAtomicExpr(st.expr),
                .return_stmt => |st| if (st.value) |v| try self.collectAtomicExpr(v),
                .if_stmt => |st| {
                    try self.collectAtomicExpr(st.condition);
                    try self.collectAtomicBlock(st.then_block);
                    if (st.else_block) |eb| try self.collectAtomicBlock(eb);
                },
                .while_stmt => |st| {
                    try self.collectAtomicExpr(st.condition);
                    try self.collectAtomicBlock(st.body);
                },
            }
        }
    }

    fn collectAtomics(self: *Lowerer, stage: shader_ir.StageDecl) !void {
        self.atomic_resources = .{};
        try self.collectAtomicBlock(stage.entry.body);
        for (self.program.functions) |function_decl| {
            try self.collectAtomicBlock(function_decl.body);
        }
    }

    fn emitStage(self: *Lowerer, stage: shader_ir.StageDecl) ![]const u8 {
        try self.collectAtomics(stage);
        var out: std.Io.Writer.Allocating = .init(self.allocator);
        try out.writer.writeAll("// generated by Kira KSL MSL backend\n");
        try out.writer.writeAll("#include <metal_stdlib>\nusing namespace metal;\n\n");
        try self.emitStructs(&out.writer);
        try self.emitOptions(&out.writer);
        try self.emitHelpers(&out.writer);
        try self.emitFunction(&out.writer, stage.entry, true);
        try self.emitStageEntry(&out.writer, stage);
        return out.toOwnedSlice();
    }

    fn typeHasBuiltins(type_decl: shader_ir.TypeDecl) bool {
        for (type_decl.fields) |field_decl| {
            if (field_decl.builtin != null) return true;
        }
        return false;
    }

    fn emitStructs(self: *Lowerer, writer: anytype) !void {
        for (self.program.types) |type_decl| {
            // A vertex input type that carries builtins (vertex_index/instance_index)
            // cannot be a [[stage_in]] struct (stage_in members must be attributes).
            // Emit it as a PLAIN struct plus a companion `{name}_attrs` stage_in
            // struct holding only the attributed fields; the stage entry
            // reconstructs the full input (builtins arrive as entry params).
            const split_vertex_input = self.shader.kind != .compute and
                isVertexInputType(self.shader.stages, type_decl.name) and
                typeHasBuiltins(type_decl);
            try writer.print("struct {s} {{\n", .{sanitizeName(type_decl.name)});
            var location: u32 = 0;
            for (type_decl.fields) |field_decl| {
                try writer.print("    {s} {s}", .{ try mslTypeName(self.allocator, field_decl.ty), sanitizeName(field_decl.name) });
                // Compute input structs are plain containers: builtins like
                // thread_position_in_grid are attached to the kernel's params, and are
                // illegal inside a struct declaration. Emit no interface attributes.
                if (self.shader.kind != .compute and !split_vertex_input) {
                    if (self.interfaceFieldAttribute(type_decl.name, field_decl, location)) |attribute| {
                        try writer.print(" {s}", .{attribute});
                        if (field_decl.builtin == null) location += 1;
                    } else if (isInterfaceType(self.shader.stages, type_decl.name) and field_decl.builtin == null) {
                        try writer.print(" [[user(locn{d})]]", .{location});
                        location += 1;
                    }
                }
                try writer.writeAll(";\n");
            }
            try writer.writeAll("};\n\n");
            if (split_vertex_input) {
                try writer.print("struct {s}_attrs {{\n", .{sanitizeName(type_decl.name)});
                var attr_location: u32 = 0;
                for (type_decl.fields) |field_decl| {
                    if (field_decl.builtin != null) continue;
                    try writer.print("    {s} {s} [[attribute({d})]];\n", .{ try mslTypeName(self.allocator, field_decl.ty), sanitizeName(field_decl.name), attr_location });
                    attr_location += 1;
                }
                try writer.writeAll("};\n\n");
            }
        }
    }

    fn interfaceFieldAttribute(self: *Lowerer, type_name: []const u8, field_decl: shader_ir.FieldDecl, location: u32) ?[]const u8 {
        if (!isInterfaceType(self.shader.stages, type_name)) return null;
        if (field_decl.builtin) |builtin| return mslBuiltinAttribute(builtin);
        if (isVertexInputType(self.shader.stages, type_name)) {
            return std.fmt.allocPrint(self.allocator, "[[attribute({d})]]", .{location}) catch null;
        }
        if (isFragmentOutputType(self.shader.stages, type_name)) {
            return std.fmt.allocPrint(self.allocator, "[[color({d})]]", .{location}) catch null;
        }
        return std.fmt.allocPrint(self.allocator, "[[user(locn{d})]]", .{location}) catch null;
    }

    fn emitOptions(self: *Lowerer, writer: anytype) !void {
        for (self.shader.options) |option_decl| {
            try writer.print("constant {s} {s} = ", .{ try mslTypeName(self.allocator, option_decl.ty), sanitizeName(option_decl.name) });
            try emitConstValue(writer, option_decl.default_value);
            try writer.writeAll(";\n");
        }
        if (self.shader.options.len != 0) try writer.writeByte('\n');
    }

    fn emitHelpers(self: *Lowerer, writer: anytype) !void {
        for (self.program.functions) |function_decl| {
            try self.emitFunction(writer, function_decl, false);
        }
    }

    fn emitFunction(self: *Lowerer, writer: anytype, function_decl: shader_ir.FunctionDecl, include_resources: bool) !void {
        try writer.print("{s} {s}(", .{ try mslTypeName(self.allocator, function_decl.return_type), sanitizeName(function_decl.name) });
        var has_param = false;
        for (function_decl.params) |param_decl| {
            if (has_param) try writer.writeAll(", ");
            try writer.print("{s} {s}", .{ try mslTypeName(self.allocator, param_decl.ty), sanitizeName(param_decl.name) });
            has_param = true;
        }
        if (include_resources) {
            try self.emitResourceParams(writer, false, &has_param, 0);
        }
        try writer.writeAll(") ");
        try emitBlock(self.allocator, writer, function_decl.body, 0);
        try writer.writeAll("\n\n");
    }

    fn findType(self: *Lowerer, name: []const u8) ?shader_ir.TypeDecl {
        for (self.program.types) |type_decl| {
            if (std.mem.eql(u8, type_decl.name, name)) return type_decl;
        }
        return null;
    }

    fn emitComputeEntry(self: *Lowerer, writer: anytype, stage: shader_ir.StageDecl) !void {
        const entry_name = stageEntryName(self.allocator, self.shader.name, stage.kind);
        // MSL compute entry: a `kernel void` with the input struct's builtin fields as
        // individual attributed params, reconstructed into the input struct before the
        // call. Resources follow with [[buffer/texture(N)]] slots.
        try writer.print("kernel void {s}(", .{entry_name});
        var has_param = false;
        const input_type = if (stage.input_type) |input_name| self.findType(input_name) else null;
        if (input_type) |it| {
            for (it.fields) |field_decl| {
                if (has_param) try writer.writeAll(", ");
                try writer.print("{s} {s}", .{ try mslTypeName(self.allocator, field_decl.ty), sanitizeName(field_decl.name) });
                if (field_decl.builtin) |builtin| try writer.print(" {s}", .{mslBuiltinAttribute(builtin)});
                has_param = true;
            }
        }
        try self.emitResourceParams(writer, true, &has_param, 0);
        try writer.writeAll(") {\n");
        if (stage.input_type) |input_name| {
            try writer.print("    {s} kira_input;\n", .{sanitizeName(input_name)});
            if (input_type) |it| {
                for (it.fields) |field_decl| {
                    try writer.print("    kira_input.{s} = {s};\n", .{ sanitizeName(field_decl.name), sanitizeName(field_decl.name) });
                }
            }
        }
        try writer.writeAll("    ");
        try writer.print("{s}(", .{sanitizeName(stage.entry.name)});
        var has_arg = false;
        if (stage.input_type != null) {
            try writer.writeAll("kira_input");
            has_arg = true;
        }
        try self.emitResourceArgs(writer, &has_arg);
        try writer.writeAll(");\n}\n");
    }

    fn emitStageEntry(self: *Lowerer, writer: anytype, stage: shader_ir.StageDecl) !void {
        if (stage.kind == .compute) {
            return self.emitComputeEntry(writer, stage);
        }
        const entry_name = stageEntryName(self.allocator, self.shader.name, stage.kind);
        const return_type = if (stage.output_type) |output_type_name| sanitizeName(output_type_name) else "void";
        // A vertex input type carrying builtins is split (see emitStructs): the
        // attributed fields arrive as a `{name}_attrs` stage_in struct, the builtins
        // as attributed entry params, and the full input is reconstructed here.
        var split_input: ?shader_ir.TypeDecl = null;
        if (stage.kind == .vertex) {
            if (stage.input_type) |input_type_name| {
                if (self.findType(input_type_name)) |input_decl| {
                    if (typeHasBuiltins(input_decl)) split_input = input_decl;
                }
            }
        }
        try writer.print("{s} {s} {s}(", .{ @tagName(stage.kind), return_type, entry_name });
        var has_param = false;
        if (stage.input_type) |input_type_name| {
            if (split_input) |input_decl| {
                try writer.print("{s}_attrs kira_attrs [[stage_in]]", .{sanitizeName(input_type_name)});
                for (input_decl.fields) |field_decl| {
                    if (field_decl.builtin) |builtin| {
                        try writer.print(", {s} {s} {s}", .{ try mslTypeName(self.allocator, field_decl.ty), sanitizeName(field_decl.name), mslBuiltinAttribute(builtin) });
                    }
                }
            } else {
                try writer.print("{s} kira_input [[stage_in]]", .{sanitizeName(input_type_name)});
            }
            has_param = true;
        }
        try self.emitResourceParams(writer, true, &has_param, if (stage.kind == .vertex) 1 else 0);
        try writer.writeAll(") {\n");
        if (split_input) |input_decl| {
            try writer.print("    {s} kira_input;\n", .{sanitizeName(stage.input_type.?)});
            for (input_decl.fields) |field_decl| {
                if (field_decl.builtin != null) {
                    try writer.print("    kira_input.{s} = {s};\n", .{ sanitizeName(field_decl.name), sanitizeName(field_decl.name) });
                } else {
                    try writer.print("    kira_input.{s} = kira_attrs.{s};\n", .{ sanitizeName(field_decl.name), sanitizeName(field_decl.name) });
                }
            }
        }
        try writer.writeAll("    ");
        if (stage.output_type != null) try writer.writeAll("return ");
        try writer.print("{s}(", .{sanitizeName(stage.entry.name)});
        var has_arg = false;
        if (stage.input_type != null) {
            try writer.writeAll("kira_input");
            has_arg = true;
        }
        try self.emitResourceArgs(writer, &has_arg);
        try writer.writeAll(");\n");
        try writer.writeAll("}\n");
    }

    fn emitResourceParams(self: *Lowerer, writer: anytype, include_attributes: bool, has_param: *bool, buffer_slot_base: u32) !void {
        // Vertex stage: the vertex descriptor owns [[buffer(0)]], so resource buffers
        // start at 1 — matching the Metal bind-group rule (vertex uniforms bind at
        // slot+1, fragment/compute at slot).
        var buffer_slot: u32 = buffer_slot_base;
        var texture_slot: u32 = 0;
        var sampler_slot: u32 = 0;
        for (self.shader.groups) |group_decl| {
            for (group_decl.resources) |resource_decl| {
                if (has_param.*) try writer.writeAll(", ");
                switch (resource_decl.kind) {
                    .uniform => {
                        try writer.print("constant {s}& {s}", .{ try mslTypeName(self.allocator, resource_decl.ty), sanitizeName(resource_decl.name) });
                        if (include_attributes) try writer.print(" [[buffer({d})]]", .{buffer_slot});
                        buffer_slot += 1;
                    },
                    .storage => {
                        const prefix = if (resource_decl.access == .read) "const device" else "device";
                        // A storage buffer is a runtime-sized array of its element type;
                        // bind it as `<elem>*`, not `<runtime_array>*` (which double-stars).
                        // Buffers touched by atomicAdd bind as atomic_uint (atomics-only).
                        if (self.atomic_resources.contains(resource_decl.name)) {
                            try writer.print("device atomic_uint* {s}", .{sanitizeName(resource_decl.name)});
                        } else {
                            const elem_ty = if (resource_decl.ty == .runtime_array) resource_decl.ty.runtime_array.* else resource_decl.ty;
                            try writer.print("{s} {s}* {s}", .{ prefix, try mslTypeName(self.allocator, elem_ty), sanitizeName(resource_decl.name) });
                        }
                        if (include_attributes) try writer.print(" [[buffer({d})]]", .{buffer_slot});
                        buffer_slot += 1;
                    },
                    .texture => {
                        try writer.print("{s} {s}", .{ try mslTypeName(self.allocator, resource_decl.ty), sanitizeName(resource_decl.name) });
                        if (include_attributes) try writer.print(" [[texture({d})]]", .{texture_slot});
                        texture_slot += 1;
                    },
                    .sampler => {
                        try writer.print("{s} {s}", .{ try mslTypeName(self.allocator, resource_decl.ty), sanitizeName(resource_decl.name) });
                        if (include_attributes) try writer.print(" [[sampler({d})]]", .{sampler_slot});
                        sampler_slot += 1;
                    },
                }
                has_param.* = true;
            }
        }
    }

    fn emitResourceArgs(self: *Lowerer, writer: anytype, has_arg: *bool) !void {
        for (self.shader.groups) |group_decl| {
            for (group_decl.resources) |resource_decl| {
                if (has_arg.*) try writer.writeAll(", ");
                try writer.writeAll(sanitizeName(resource_decl.name));
                has_arg.* = true;
            }
        }
    }
};

fn emitBlock(allocator: std.mem.Allocator, writer: anytype, block: shader_ir.Block, indent_level: usize) anyerror!void {
    try writer.writeAll("{\n");
    for (block.statements) |statement| {
        try emitIndent(writer, indent_level + 1);
        try emitStatement(allocator, writer, statement, indent_level + 1);
    }
    try emitIndent(writer, indent_level);
    try writer.writeAll("}");
}

fn emitStatement(allocator: std.mem.Allocator, writer: anytype, statement: shader_ir.Statement, indent_level: usize) anyerror!void {
    switch (statement) {
        .let_stmt => |let_stmt| {
            try writer.print("{s} {s}", .{ try mslTypeName(allocator, let_stmt.ty), sanitizeName(let_stmt.name) });
            if (let_stmt.value) |value| {
                try writer.writeAll(" = ");
                try emitExpr(allocator, writer, value);
            }
            try writer.writeAll(";\n");
        },
        .assign_stmt => |assign_stmt| {
            try emitExpr(allocator, writer, assign_stmt.target);
            try writer.writeAll(" = ");
            try emitExpr(allocator, writer, assign_stmt.value);
            try writer.writeAll(";\n");
        },
        .expr_stmt => |expr_stmt| {
            try emitExpr(allocator, writer, expr_stmt.expr);
            try writer.writeAll(";\n");
        },
        .return_stmt => |return_stmt| {
            if (return_stmt.value) |value| {
                try writer.writeAll("return ");
                try emitExpr(allocator, writer, value);
                try writer.writeAll(";\n");
            } else {
                try writer.writeAll("return;\n");
            }
        },
        .if_stmt => |if_stmt| {
            try writer.writeAll("if (");
            try emitExpr(allocator, writer, if_stmt.condition);
            try writer.writeAll(") ");
            try emitBlock(allocator, writer, if_stmt.then_block, indent_level);
            if (if_stmt.else_block) |else_block| {
                try writer.writeAll(" else ");
                try emitBlock(allocator, writer, else_block, indent_level);
            }
            try writer.writeAll("\n");
        },
        .while_stmt => |while_stmt| {
            try writer.writeAll("while (");
            try emitExpr(allocator, writer, while_stmt.condition);
            try writer.writeAll(") ");
            try emitBlock(allocator, writer, while_stmt.body, indent_level);
            try writer.writeAll("\n");
        },
    }
}

fn emitExpr(allocator: std.mem.Allocator, writer: anytype, expr: *const shader_ir.Expr) anyerror!void {
    switch (expr.node) {
        .const_value => |value| try emitConstValue(writer, value),
        .name => |name_ref| try writer.writeAll(sanitizeName(name_ref.name)),
        .unary => |unary_expr| {
            try writer.writeAll(switch (unary_expr.op) {
                .neg => "-",
                .not => "!",
            });
            try emitExpr(allocator, writer, unary_expr.operand);
        },
        .binary => |binary_expr| {
            try writer.writeByte('(');
            try emitExpr(allocator, writer, binary_expr.left);
            try writer.writeAll(switch (binary_expr.op) {
                .add => " + ",
                .sub => " - ",
                .mul => " * ",
                .div => " / ",
                .less => " < ",
                .less_equal => " <= ",
                .greater => " > ",
                .greater_equal => " >= ",
                .equal => " == ",
                .not_equal => " != ",
            });
            try emitExpr(allocator, writer, binary_expr.right);
            try writer.writeByte(')');
        },
        .member => |member_expr| {
            try emitExpr(allocator, writer, member_expr.object);
            try writer.print(".{s}", .{sanitizeName(member_expr.name)});
        },
        .index => |index_expr| {
            try emitExpr(allocator, writer, index_expr.object);
            try writer.writeByte('[');
            try emitExpr(allocator, writer, index_expr.index);
            try writer.writeByte(']');
        },
        .call => |call_expr| switch (call_expr.callee) {
            .constructor => |ty| {
                try writer.print("{s}(", .{try mslTypeName(allocator, ty)});
                try emitCallArgs(allocator, writer, call_expr.args);
                try writer.writeByte(')');
            },
            .function => |function_name| {
                try writer.print("{s}(", .{sanitizeName(function_name.name)});
                try emitCallArgs(allocator, writer, call_expr.args);
                try writer.writeByte(')');
            },
            .intrinsic => |intrinsic| switch (intrinsic) {
                .mul => {
                    try writer.writeByte('(');
                    try emitExpr(allocator, writer, call_expr.args[0]);
                    try writer.writeAll(" * ");
                    try emitExpr(allocator, writer, call_expr.args[1]);
                    try writer.writeByte(')');
                },
                .normalize => {
                    try writer.writeAll("normalize(");
                    try emitCallArgs(allocator, writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .dot => {
                    try writer.writeAll("dot(");
                    try emitCallArgs(allocator, writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .length, .pow, .sin, .atan2, .smoothstep => {
                    try writer.print("{s}(", .{@tagName(intrinsic)});
                    try emitCallArgs(allocator, writer, call_expr.args);
                    try writer.writeByte(')');
                },
                .sample => {
                    const texture_name = switch (call_expr.args[0].node) {
                        .name => |name_ref| name_ref.name,
                        else => "unsupported_texture",
                    };
                    try writer.print("{s}.sample(", .{sanitizeName(texture_name)});
                    try emitExpr(allocator, writer, call_expr.args[1]);
                    try writer.writeAll(", ");
                    try emitExpr(allocator, writer, call_expr.args[2]);
                    try writer.writeByte(')');
                },
                .load => {
                    // texelFetch: read an unfiltered texel at integer pixel coords.
                    const texture_name = switch (call_expr.args[0].node) {
                        .name => |name_ref| name_ref.name,
                        else => "unsupported_texture",
                    };
                    try writer.print("{s}.read(uint2(", .{sanitizeName(texture_name)});
                    try emitExpr(allocator, writer, call_expr.args[1]);
                    try writer.writeAll("))");
                },
                .atomic_add => {
                    const buffer_name = switch (call_expr.args[0].node) {
                        .name => |name_ref| name_ref.name,
                        else => "unsupported_buffer",
                    };
                    try writer.print("atomic_fetch_add_explicit(&{s}[", .{sanitizeName(buffer_name)});
                    try emitExpr(allocator, writer, call_expr.args[1]);
                    try writer.writeAll("], ");
                    try emitExpr(allocator, writer, call_expr.args[2]);
                    try writer.writeAll(", memory_order_relaxed)");
                },
            },
        },
    }
}

fn emitCallArgs(allocator: std.mem.Allocator, writer: anytype, args: []const *shader_ir.Expr) anyerror!void {
    for (args, 0..) |arg, index| {
        if (index != 0) try writer.writeAll(", ");
        try emitExpr(allocator, writer, arg);
    }
}

fn emitConstValue(writer: anytype, value: shader_ir.ConstValue) !void {
    switch (value) {
        .bool => |bool_value| try writer.writeAll(if (bool_value) "true" else "false"),
        .int => |int_value| try writer.print("{d}", .{int_value}),
        .uint => |uint_value| try writer.print("{d}u", .{uint_value}),
        .float => |float_value| try emitFloatValue(writer, float_value),
    }
}

fn emitFloatValue(writer: anytype, value: f64) !void {
    try writer.print("{d}", .{value});
    if (@floor(value) == value) try writer.writeAll(".0");
}

fn emitIndent(writer: anytype, level: usize) !void {
    for (0..level) |_| try writer.writeAll("    ");
}

fn mslTypeName(allocator: std.mem.Allocator, ty: shader_model.Type) ![]const u8 {
    return switch (ty) {
        .void => "void",
        .scalar => switch (ty.scalar) {
            .bool => "bool",
            .int => "int",
            .uint => "uint",
            .float => "float",
        },
        .vector => try std.fmt.allocPrint(allocator, "{s}{d}", .{ try mslScalarName(ty.vector.scalar), ty.vector.width }),
        .matrix => try std.fmt.allocPrint(allocator, "float{d}x{d}", .{ ty.matrix.columns, ty.matrix.rows }),
        .struct_ref => sanitizeName(ty.struct_ref),
        .texture => mslTextureName(ty.texture),
        .sampler => switch (ty.sampler) {
            .filtering, .comparison => "sampler",
        },
        .runtime_array => try std.fmt.allocPrint(allocator, "{s}*", .{try mslTypeName(allocator, ty.runtime_array.*)}),
    };
}

fn mslScalarName(scalar: shader_model.ScalarType) ![]const u8 {
    return switch (scalar) {
        .bool => "bool",
        .int => "int",
        .uint => "uint",
        .float => "float",
    };
}

fn mslTextureName(texture: shader_model.TextureDimension) []const u8 {
    return switch (texture) {
        .texture_2d => "texture2d<float>",
        .texture_2d_uint => "texture2d<uint>",
        .texture_cube => "texturecube<float>",
        .depth_2d => "depth2d<float>",
    };
}

fn mslBuiltinAttribute(builtin: shader_model.Builtin) []const u8 {
    return switch (builtin) {
        .position => "[[position]]",
        .vertex_index => "[[vertex_id]]",
        .instance_index => "[[instance_id]]",
        .front_facing => "[[front_facing]]",
        .frag_coord => "[[position]]",
        .thread_id => "[[thread_position_in_grid]]",
        .local_id => "[[thread_position_in_threadgroup]]",
        .group_id => "[[threadgroup_position_in_grid]]",
        .local_index => "[[thread_index_in_threadgroup]]",
    };
}

fn isInterfaceType(stages: []const shader_ir.StageDecl, type_name: []const u8) bool {
    for (stages) |stage| {
        if (stage.input_type) |input_type| {
            if (std.mem.eql(u8, input_type, type_name)) return true;
        }
        if (stage.output_type) |output_type| {
            if (std.mem.eql(u8, output_type, type_name)) return true;
        }
    }
    return false;
}

fn isVertexInputType(stages: []const shader_ir.StageDecl, type_name: []const u8) bool {
    for (stages) |stage| {
        if (stage.kind != .vertex) continue;
        if (stage.input_type) |input_type| {
            if (std.mem.eql(u8, input_type, type_name)) return true;
        }
    }
    return false;
}

fn isFragmentOutputType(stages: []const shader_ir.StageDecl, type_name: []const u8) bool {
    for (stages) |stage| {
        if (stage.kind != .fragment) continue;
        if (stage.output_type) |output_type| {
            if (std.mem.eql(u8, output_type, type_name)) return true;
        }
    }
    return false;
}

fn findStage(stages: []const shader_ir.StageDecl, stage: shader_model.Stage) ?shader_ir.StageDecl {
    for (stages) |stage_decl| {
        if (stage_decl.kind == stage) return stage_decl;
    }
    return null;
}

fn sanitizeName(name: []const u8) []const u8 {
    if (reservedMslReplacement(name)) |replacement| return replacement;
    return name;
}

fn reservedMslReplacement(name: []const u8) ?[]const u8 {
    const reserved = [_]struct { name: []const u8, replacement: []const u8 }{
        .{ .name = "bool", .replacement = "kira_bool" },
        .{ .name = "break", .replacement = "kira_break" },
        .{ .name = "case", .replacement = "kira_case" },
        .{ .name = "constant", .replacement = "kira_constant" },
        .{ .name = "continue", .replacement = "kira_continue" },
        .{ .name = "device", .replacement = "kira_device" },
        .{ .name = "else", .replacement = "kira_else" },
        .{ .name = "false", .replacement = "kira_false" },
        .{ .name = "float", .replacement = "kira_float" },
        .{ .name = "fragment", .replacement = "kira_fragment" },
        .{ .name = "if", .replacement = "kira_if" },
        .{ .name = "int", .replacement = "kira_int" },
        .{ .name = "kernel", .replacement = "kira_kernel" },
        .{ .name = "return", .replacement = "kira_return" },
        .{ .name = "sampler", .replacement = "kira_sampler" },
        .{ .name = "struct", .replacement = "kira_struct" },
        .{ .name = "texture2d", .replacement = "kira_texture2d" },
        .{ .name = "thread", .replacement = "kira_thread" },
        .{ .name = "true", .replacement = "kira_true" },
        .{ .name = "uint", .replacement = "kira_uint" },
        .{ .name = "using", .replacement = "kira_using" },
        .{ .name = "vertex", .replacement = "kira_vertex" },
        .{ .name = "void", .replacement = "kira_void" },
        .{ .name = "while", .replacement = "kira_while" },
    };
    for (reserved) |entry| {
        if (std.mem.eql(u8, name, entry.name)) return entry.replacement;
    }
    return null;
}

fn stageEntryName(allocator: std.mem.Allocator, shader_name: []const u8, stage: shader_model.Stage) []const u8 {
    return std.fmt.allocPrint(allocator, "{s}__{s}__main", .{ sanitizeName(shader_name), @tagName(stage) }) catch shader_name;
}

test "sanitizes MSL reserved local names" {
    try std.testing.expectEqualStrings("kira_thread", sanitizeName("thread"));
    try std.testing.expectEqualStrings("kira_vertex", sanitizeName("vertex"));
    try std.testing.expectEqualStrings("result", sanitizeName("result"));
}
